---
- name: AUTOMATIC BACKUP OF RUNNING-CONFIG
  hosts: routers
  gather_facts: false
  connection: ansible.netcommon.network_cli
  vars:
    ansible_command_timeout: 120
    student_id: "66070136"

  tasks:
    - name: DISPLAYING THE RUNNING-CONFIG
      ansible.netcommon.cli_command:
        command: show running-config
      register: config

    - name: GET ROUTER HOSTNAME
      ansible.netcommon.cli_command:
        command: show running-config | include hostname
      register: hostname_output

    - name: EXTRACT HOSTNAME
      set_fact:
        router_name: "{{ hostname_output.stdout | regex_search('hostname (.+)', '\\1') | first }}"

    - name: SAVE OUTPUT TO CURRENT DIRECTORY
      copy:
        content: "{{ config.stdout }}"
        dest: "./show_run_{{ student_id }}_{{ router_name }}.txt"
      delegate_to: localhost
